server:
  port: 8090
  servlet:
    context-path: /ossapp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/OssApp?currentSchema=OssAppRepository
    username: user1
    password: 1111
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
